# Codecov configuration
coverage:
  precision: 2
  round: down
  range: "70...95"
  
  status:
    project:
      default:
        target: 75%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 70%
        threshold: 2%
        informational: false

  flags:
    frontend:
      paths:
        - frontend/src/
      target: 70%
    backend:
      paths:
        - backend/src/
      target: 75%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/setupTests.js"
  - "**/testUtils.js"
  - "frontend/src/index.js"
  - "frontend/src/reportWebVitals.js"
  - "backend/tests/"
  - "frontend/src/**/__tests__/"
  - "backend/src/**/__tests__/"
  - "*.md"
  - "docs/"
  - "scripts/"
  - "utilities/"