version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=your_db_user
      - DB_HOST=db
      - DB_NAME=your_db_name
      - DB_PASSWORD=your_db_password
      - DB_PORT=5432
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
      - OPENAI_API_KEY=your_openai_api_key
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/item_data.sql:/docker-entrypoint-initdb.d/02-item_data.sql
      - ./database/mod_data.sql:/docker-entrypoint-initdb.d/03-mod_data.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: