# Build and serve stage
FROM node:18

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

# Add this line to create a .env file with the API URL
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

RUN npm run build

# Install serve to run the application
RUN npm install -g serve

EXPOSE 80

# Serve the app
CMD ["serve", "-s", "build", "-l", "80"]