INSERT INTO mod (name, plus, type, valuecalc, target, subtarget) VALUES
(E'Living Steel', NULL, E'Material', E'+10', E'weapon', E'ammunition'),
(E'Spiresteel', NULL, E'Material', E'+10', E'weapon', E'ammunition'),
(E'Druchite', NULL, E'Material', E'+12', E'weapon', E'ammunition'),
(E'Fire-forged Steel', NULL, E'Material', E'+15', E'weapon', E'ammunition'),
(E'Frost-forged Steel', NULL, E'Material', E'+15', E'weapon', E'ammunition'),
(E'Alchemical Silver', NULL, E'Material', E'+2', E'weapon', E'ammunition'),
(E'Elysian Bronze', NULL, E'Material', E'+20', E'weapon', E'ammunition'),
(E'Blood Crystal', NULL, E'Material', E'+30', E'weapon', E'ammunition'),
(E'Reinforced Viridium', NULL, E'Material', E'+40', E'weapon', E'ammunition'),
(E'Adamantine', NULL, E'Material', E'+60', E'weapon', E'ammunition'),
(E'Aszite', NULL, E'Material', E'+1000', E'armor', E'heavy'),
(E'Noqual', NULL, E'Material', E'+12000', E'armor', E'heavy'),
(E'Singing Steel', NULL, E'Material', E'+12000', E'armor', E'heavy'),
(E'Living Steel', NULL, E'Material', E'+1500', E'armor', E'heavy'),
(E'Adamantine', NULL, E'Material', E'+15000', E'armor', E'heavy'),
(E'Druchite', NULL, E'Material', E'+2000', E'armor', E'heavy'),
(E'Elysian Bronze', NULL, E'Material', E'+3000', E'armor', E'heavy'),
(E'Fire-forged Steel', NULL, E'Material', E'+3000', E'armor', E'heavy'),
(E'Frost-forged Steel', NULL, E'Material', E'+3000', E'armor', E'heavy'),
(E'Spiresteel', NULL, E'Material', E'+3000', E'armor', E'heavy'),
(E'Lazurite-Bonded', NULL, E'Material', E'+3500', E'armor', E'heavy'),
(E'Voidglass', NULL, E'Material', E'+4500', E'armor', E'heavy'),
(E'Horacalcum', NULL, E'Material', E'+60000', E'armor', E'heavy'),
(E'Mithral', NULL, E'Material', E'+9000', E'armor', E'heavy'),
(E'Angelskin', NULL, E'Material', E'+1000', E'armor', E'light'),
(E'Druchite', NULL, E'Material', E'+1000', E'armor', E'light'),
(E'Elysian Bronze', NULL, E'Material', E'+1000', E'armor', E'light'),
(E'Fire-forged Steel', NULL, E'Material', E'+1000', E'armor', E'light'),
(E'Frost-forged Steel', NULL, E'Material', E'+1000', E'armor', E'light'),
(E'Mithral', NULL, E'Material', E'+1000', E'armor', E'light'),
(E'Spiresteel', NULL, E'Material', E'+1000', E'armor', E'light'),
(E'Voidglass', NULL, E'Material', E'+1000', E'armor', E'light'),
(E'Horacalcum', NULL, E'Material', E'+10000', E'armor', E'light'),
(E'Eel Hide', NULL, E'Material', E'+1200', E'armor', E'light'),
(E'Lazurite-Bonded', NULL, E'Material', E'+1500', E'armor', E'light'),
(E'Noqual', NULL, E'Material', E'+4000', E'armor', E'light'),
(E'Living Steel', NULL, E'Material', E'+500', E'armor', E'light'),
(E'Adamantine', NULL, E'Material', E'+5000', E'armor', E'light'),
(E'Aszite', NULL, E'Material', E'+750', E'armor', E'light'),
(E'Darkleaf Cloth', NULL, E'Material', E'+750', E'armor', E'light'),
(E'Singing Steel', NULL, E'Material', E'+750', E'armor', E'light'),
(E'Heatstone Plating', NULL, E'Material', E'+800', E'armor', E'light'),
(E'Alchemical Silver', NULL, E'Material', E'+20', E'weapon', E'light'),
(E'Heatstone Plating', NULL, E'Material', E'+1000', E'armor', E'medium'),
(E'Living Steel', NULL, E'Material', E'+1000', E'armor', E'medium'),
(E'Adamantine', NULL, E'Material', E'+10000', E'armor', E'medium'),
(E'Darkleaf Cloth', NULL, E'Material', E'+1500', E'armor', E'medium'),
(E'Druchite', NULL, E'Material', E'+1500', E'armor', E'medium'),
(E'Eel Hide', NULL, E'Material', E'+1800', E'armor', E'medium'),
(E'Angelskin', NULL, E'Material', E'+2000', E'armor', E'medium'),
(E'Elysian Bronze', NULL, E'Material', E'+2000', E'armor', E'medium'),
(E'Spiresteel', NULL, E'Material', E'+2000', E'armor', E'medium'),
(E'Voidglass', NULL, E'Material', E'+2000', E'armor', E'medium'),
(E'Fire-forged Steel', NULL, E'Material', E'+2500', E'armor', E'medium'),
(E'Frost-forged Steel', NULL, E'Material', E'+2500', E'armor', E'medium'),
(E'Lazurite-Bonded', NULL, E'Material', E'+2500', E'armor', E'medium'),
(E'Horacalcum', NULL, E'Material', E'+30000', E'armor', E'medium'),
(E'Mithral', NULL, E'Material', E'+4000', E'armor', E'medium'),
(E'Aszite', NULL, E'Material', E'+750', E'armor', E'medium'),
(E'Noqual', NULL, E'Material', E'+8000', E'armor', E'medium'),
(E'Singing Steel', NULL, E'Material', E'+9000', E'armor', E'medium'),
(E'Alchemical Silver', NULL, E'Material', E'+90', E'weapon', E'one handed'),
(E'Living Steel', NULL, E'Material', E'+100', E'armor', E'shield'),
(E'Mithral', NULL, E'Material', E'+1000', E'armor', E'shield'),
(E'Noqual', NULL, E'Material', E'+2000', E'armor', E'shield'),
(E'Voidglass', NULL, E'Material', E'+3000', E'armor', E'shield'),
(E'Singing Steel', NULL, E'Material', E'+7000', E'armor', E'shield'),
(E'Alchemical Silver', NULL, E'Material', E'+180', E'weapon', E'two handed'),
(E'+1', 1, E'Power', NULL, E'armor', NULL),
(E'+1', 1, E'Power', NULL, E'weapon', NULL),
(E'Versatile Design', NULL, E'Power', E'+500', E'weapon', NULL),
(E'Vital Guard', NULL, E'Power', E'+500', E'armor', NULL),
(E'Vitalguard', NULL, E'Power', E'+500', E'armor', NULL),
(E'Cryptstone', NULL, E'Material', E'+500', E'weapon', NULL),
(E'Whipwood', NULL, E'Material', E'+500', E'weapon', NULL),
(E'Living Steel', NULL, E'Material', E'+500', E'weapon', NULL),
(E'Noqual', NULL, E'Material', E'+500', E'weapon', NULL),
(E'Buoyant', NULL, E'Power', E'+500', E'armor', NULL),
(E'Cloudburst', NULL, E'Power', E'+5000', E'armor', NULL),
(E'Comfort', NULL, E'Power', E'+5000', E'armor', NULL),
(E'Corsair', NULL, E'Power', E'+5000', E'armor', NULL),
(E'Creeping', NULL, E'Power', E'+5000', E'armor', NULL),
(E'Deceiving', NULL, E'Power', E'+5000', E'armor', NULL),
(E'Malevolent', NULL, E'Power', E'+5000', E'armor', NULL),
(E'Rallying', NULL, E'Power', E'+5000', E'armor', NULL),
(E'Sacrosanct', NULL, E'Power', E'+5000', E'weapon', NULL),
(E'Sneaky', NULL, E'Power', E'+5000', E'weapon', NULL),
(E'Wyrmsbreath', NULL, E'Power', E'+5000', E'armor', NULL),
(E'Inubrix', NULL, E'Material', E'+5000', E'weapon', NULL),
(E'Fire-forged Steel', NULL, E'Material', E'+600', E'weapon', NULL),
(E'Frost-forged Steel', NULL, E'Material', E'+600', E'weapon', NULL),
(E'Spirit-Bonded', NULL, E'Power', E'+6000', E'armor', NULL),
(E'Horacalcum', NULL, E'Material', E'+6000', E'weapon', NULL),
(E'Siccatite (Cold)', NULL, E'Material', E'+6000', E'armor', NULL),
(E'Siccatite (Hot)', NULL, E'Material', E'+6000', E'armor', NULL),
(E'Singing Steel', NULL, E'Material', E'+6000', E'weapon', NULL),
(E'Sunsilk', NULL, E'Material', E'+6000', E'armor', NULL),
(E'locksmith', NULL, E'Power', E'+6500', E'armor', NULL),
(E'Acid Resistance, Greater', NULL, E'Power', E'+66000', E'armor', NULL),
(E'Cold Resistance, greater', NULL, E'Power', E'+66000', E'armor', NULL),
(E'Electricity Resistance, Greater', NULL, E'Power', E'+66000', E'armor', NULL),
(E'Fire Resistance, Greater', NULL, E'Power', E'+66000', E'armor', NULL),
(E'Sonic Resistance, greater', NULL, E'Power', E'+66000', E'armor', NULL),
(E'Adhesive', NULL, E'Power', E'+7000', E'armor', NULL),
(E'Liberating', NULL, E'Power', E'+7000', E'weapon', NULL),
(E'Spiteful', NULL, E'Power', E'+7000', E'armor', NULL),
(E'Silversheen', NULL, E'Material', E'+750', E'weapon', NULL),
(E'Concealed', NULL, E'Power', E'+7500', E'weapon', NULL),
(E'Hosteling', NULL, E'Power', E'+7500', E'armor', NULL),
(E'Radiant', NULL, E'Power', E'+7500', E'armor', NULL),
(E'Sniping, Improved', NULL, E'Power', E'+7500', E'weapon', NULL),
(E'Trackless', NULL, E'Power', E'+7500', E'armor', NULL),
(E'Shield Boss, hooked', NULL, E'Power', E'+80', E'armor', NULL),
(E'Shield Boss, mwk reinforcing', NULL, E'Power', E'+80', E'armor', NULL),
(E'Liquid Glass', NULL, E'Material', E'+800', E'weapon', NULL),
(E'Liquid Glass', NULL, E'Material', E'+800', E'armor', NULL),
(E'Laser sight', NULL, E'Power', E'+8000', E'weapon', NULL),
(E'Shield Boss, mwk illuminating', NULL, E'Power', E'+85', E'armor', NULL),
(E'Heavy Weapon Harness', NULL, E'Power', E'+9000', E'armor', NULL),
(E'Phase Lurching', NULL, E'Power', E'+9100', E'armor', NULL),
(E'Advancing', 1, E'Power', NULL, E'armor', NULL),
(E'Agile', 1, E'Power', NULL, E'weapon', NULL),
(E'Allying', 1, E'Power', NULL, E'weapon', NULL),
(E'Ambushing', 1, E'Power', NULL, E'weapon', NULL),
(E'Answering', 1, E'Power', NULL, E'weapon', NULL),
(E'Arrow Catching', 1, E'Power', NULL, E'armor', NULL),
(E'Assiduous', 1, E'Power', NULL, E'armor', NULL),
(E'Balanced', 1, E'Power', NULL, E'armor', NULL),
(E'Abysium', NULL, E'Material', E'*1', E'weapon', NULL),
(E'Abysium', NULL, E'Material', E'*1', E'armor', NULL),
(E'Bronze', NULL, E'Material', E'*1', E'weapon', NULL),
(E'Bronze', NULL, E'Material', E'*1', E'armor', NULL),
(E'Aligned', NULL, E'Power', E'*1.1', E'armor', NULL),
(E'Aligned', NULL, E'Power', E'*1.1', E'weapon', NULL),
(E'Enhanced', NULL, E'Power', E'*1.1', E'weapon', NULL),
(E'Reinforced', NULL, E'Power', E'*1.1', E'armor', NULL),
(E'Reinforced', NULL, E'Power', E'*1.1', E'weapon', NULL),
(E'Nexavaran Steel', NULL, E'Material', E'*1.5', E'weapon', NULL),
(E'Gold', NULL, E'Material', E'*10', E'weapon', NULL),
(E'Gold', NULL, E'Material', E'*10', E'armor', NULL),
(E'Cold Iron', NULL, E'Material', E'*2', E'weapon', NULL),
(E'Dragonhide', NULL, E'Material', E'*2', E'armor', NULL),
(E'Glaucite', NULL, E'Material', E'*3', E'weapon', NULL),
(E'Glaucite', NULL, E'Material', E'*3', E'armor', NULL),
(E'Gold Plated', NULL, E'Material', E'*3', E'weapon', NULL),
(E'Gold Plated', NULL, E'Material', E'*3', E'armor', NULL),
(E'Bone', NULL, E'Material', E'/2', E'weapon', NULL),
(E'Bone', NULL, E'Material', E'/2', E'armor', NULL),
(E'Glass', NULL, E'Material', E'/2', E'weapon', NULL),
(E'Obsidian', NULL, E'Material', E'/2', E'weapon', NULL),
(E'Stone', NULL, E'Material', E'/4', E'weapon', NULL),
(E'Darkwood', NULL, E'Material', E'+(10*item.wgt)', E'weapon', NULL),
(E'Darkwood', NULL, E'Material', E'+(10*item.wgt)', E'armor', NULL),
(E'Paueliel', NULL, E'Material', E'+(15*item.wgt)', E'weapon', NULL),
(E'Paueliel', NULL, E'Material', E'+(15*item.wgt)', E'armor', NULL),
(E'Blackwood', NULL, E'Material', E'+(20*item.wgt)', E'weapon', NULL),
(E'Blackwood', NULL, E'Material', E'+(20*item.wgt)', E'armor', NULL),
(E'Sunsilver', NULL, E'Material', E'+(25*item.wgt)', E'weapon', NULL),
(E'Sunsilver', NULL, E'Material', E'+(25*item.wgt)', E'armor', NULL),
(E'Greenwood', NULL, E'Material', E'+(50*item.wgt)', E'weapon', NULL),
(E'Greenwood', NULL, E'Material', E'+(50*item.wgt)', E'armor', NULL),
(E'Shield Spikes', NULL, E'Power', E'+10', E'armor', NULL),
(E'Caphorite', NULL, E'Material', E'+10', E'weapon', NULL),
(E'Armor Vents', NULL, E'Power', E'+100', E'armor', NULL),
(E'Consecrated', NULL, E'Power', E'+100', E'armor', NULL),
(E'Adaptive', NULL, E'Power', E'+1000', E'weapon', NULL),
(E'Cushioned', NULL, E'Power', E'+1000', E'armor', NULL),
(E'Deflecting', NULL, E'Power', E'+1000', E'armor', NULL),
(E'Double-Plated', NULL, E'Power', E'+1000', E'armor', NULL),
(E'Jagged Hook', NULL, E'Power', E'+1000', E'weapon', NULL),
(E'Jarring', NULL, E'Power', E'+1000', E'armor', NULL),
(E'Nimble', NULL, E'Power', E'+1000', E'armor', NULL),
(E'Razor-Sharp', NULL, E'Power', E'+1000', E'weapon', NULL),
(E'Shrinking', NULL, E'Power', E'+1000', E'weapon', NULL),
(E'Wyroot (1 Point)', NULL, E'Material', E'+1000', E'weapon', NULL),
(E'Elysian Bronze', NULL, E'Material', E'+1000', E'weapon', NULL),
(E'Siccatite (Cold)', NULL, E'Material', E'+1000', E'weapon', NULL),
(E'Siccatite (Hot)', NULL, E'Material', E'+1000', E'weapon', NULL),
(E'Voidglass', NULL, E'Material', E'+1000', E'weapon', NULL),
(E'Mithral', NULL, E'Material', E'+1000', E'weapon', NULL),
(E'Delving', NULL, E'Power', E'+10000', E'armor', NULL),
(E'Putrid', NULL, E'Power', E'+10000', E'armor', NULL),
(E'Transformative', NULL, E'Power', E'+10000', E'weapon', NULL),
(E'Shield Boss, breakaway', NULL, E'Power', E'+120', E'armor', NULL),
(E'Druchite', NULL, E'Material', E'+1200', E'weapon', NULL),
(E'Reinforced Viridium', NULL, E'Material', E'+1200', E'weapon', NULL),
(E'Shield Boss, mwk hooked', NULL, E'Power', E'+130', E'armor', NULL),
(E'Throneglass', NULL, E'Material', E'+13000', E'weapon', NULL),
(E'Razored', NULL, E'Power', E'+1350', E'armor', NULL),
(E'Dueling', NULL, E'Power', E'+14000', E'weapon', NULL),
(E'Consecrated', NULL, E'Power', E'+150', E'weapon', NULL),
(E'Brutally Weighted', NULL, E'Power', E'+1500', E'weapon', NULL),
(E'Blood Crystal', NULL, E'Material', E'+1500', E'weapon', NULL),
(E'Aquadynamic, Improved', NULL, E'Power', E'+15000', E'armor', NULL),
(E'Harmonizing', NULL, E'Power', E'+15000', E'armor', NULL),
(E'Radiant Flight', NULL, E'Power', E'+15000', E'armor', NULL),
(E'Shadow, Improved', NULL, E'Power', E'+15000', E'armor', NULL),
(E'Slick, Improved', NULL, E'Power', E'+15000', E'armor', NULL),
(E'Transformative, Greater', NULL, E'Power', E'+15000', E'weapon', NULL),
(E'Venom-Eating', NULL, E'Power', E'+15000', E'armor', NULL),
(E'Sniping, Greater', NULL, E'Power', E'+16875', E'weapon', NULL),
(E'Shield Boss, mwk breakaway', NULL, E'Power', E'+170', E'armor', NULL),
(E'Acid Resistance', NULL, E'Power', E'+18000', E'armor', NULL),
(E'Channeling, Negative', NULL, E'Power', E'+18000', E'armor', NULL),
(E'Channeling, Positive', NULL, E'Power', E'+18000', E'armor', NULL),
(E'Cold Resistance', NULL, E'Power', E'+18000', E'armor', NULL),
(E'Electricity Resistance', NULL, E'Power', E'+18000', E'armor', NULL),
(E'Fire Resistance', NULL, E'Power', E'+18000', E'armor', NULL),
(E'Martyring', NULL, E'Power', E'+18000', E'armor', NULL),
(E'Sonic Resistance', NULL, E'Power', E'+18000', E'armor', NULL),
(E'Sniping', NULL, E'Power', E'+1875', E'weapon', NULL),
(E'Armored Kilt', NULL, E'Power', E'+20', E'armor', NULL),
(E'Griffon Mane', NULL, E'Material', E'+200', E'armor', NULL),
(E'Viridium', NULL, E'Material', E'+200', E'weapon', NULL),
(E'Dual- Balanced', NULL, E'Power', E'+2000', E'weapon', NULL),
(E'Fitting', NULL, E'Power', E'+2000', E'armor', NULL),
(E'Phantom ammunition', NULL, E'Power', E'+2000', E'weapon', NULL),
(E'Serrated Edge', NULL, E'Power', E'+2000', E'weapon', NULL),
(E'Tactically Adapted', NULL, E'Power', E'+2000', E'weapon', NULL),
(E'Wyroot (2 Point)', NULL, E'Material', E'+2000', E'weapon', NULL),
(E'Spiresteel', NULL, E'Material', E'+2000', E'weapon', NULL),
(E'Poison resistant', NULL, E'Power', E'+2250', E'armor', NULL),
(E'Reliquary (Holy)', NULL, E'Power', E'+250', E'armor', NULL),
(E'Reliquary (Holy)', NULL, E'Power', E'+250', E'weapon', NULL),
(E'Reliquary (Unholy)', NULL, E'Power', E'+250', E'armor', NULL),
(E'Reliquary (Unholy)', NULL, E'Power', E'+250', E'weapon', NULL),
(E'Prehensile', NULL, E'Power', E'+2500', E'weapon', NULL),
(E'Glamered', NULL, E'Power', E'+2700', E'armor', NULL),
(E'Righteous', NULL, E'Power', E'+27000', E'armor', NULL),
(E'Unbound', NULL, E'Power', E'+27000', E'armor', NULL),
(E'Unrighteous', NULL, E'Power', E'+27000', E'armor', NULL),
(E'Vigilant', NULL, E'Power', E'+27000', E'armor', NULL),
(E'Dry load', NULL, E'Power', E'+30', E'weapon', NULL),
(E'Shield Boss, reinforcing', NULL, E'Power', E'+30', E'armor', NULL),
(E'Spike Hilt', NULL, E'Power', E'+300', E'weapon', NULL),
(E'Undine weaponshaft', NULL, E'Power', E'+300', E'weapon', NULL),
(E'Concealed, Lesser', NULL, E'Power', E'+3000', E'weapon', NULL),
(E'Impervious', NULL, E'Power', E'+3000', E'weapon', NULL),
(E'Mental Focus', NULL, E'Power', E'+3000', E'armor', NULL),
(E'Adamantine', NULL, E'Material', E'+3000', E'weapon', NULL),
(E'Determination', NULL, E'Power', E'+30000', E'armor', NULL),
(E'Shield Boss, reinforcing tower', NULL, E'Power', E'+330', E'armor', NULL),
(E'Shield Boss, illuminating tower', NULL, E'Power', E'+335', E'armor', NULL),
(E'Aquadynamic, Greater', NULL, E'Power', E'+33750', E'armor', NULL),
(E'Shadow, Greater', NULL, E'Power', E'+33750', E'armor', NULL),
(E'Slick, greater', NULL, E'Power', E'+33750', E'armor', NULL),
(E'Shield Boss, illuminating', NULL, E'Power', E'+35', E'armor', NULL),
(E'Aquadynamic', NULL, E'Power', E'+3750', E'armor', NULL),
(E'Exclusionary', NULL, E'Power', E'+3750', E'weapon', NULL),
(E'jousting', NULL, E'Power', E'+3750', E'armor', NULL),
(E'Shadow', NULL, E'Power', E'+3750', E'armor', NULL),
(E'Slick', NULL, E'Power', E'+3750', E'armor', NULL),
(E'Shield Boss, hooked tower', NULL, E'Power', E'+380', E'armor', NULL),
(E'Shield Boss, mwk reinforcing tower', NULL, E'Power', E'+380', E'armor', NULL),
(E'Shield Boss, mwk illuminating tower', NULL, E'Power', E'+385', E'armor', NULL),
(E'Burdenless', NULL, E'Power', E'+4000', E'armor', NULL),
(E'Expeditious', NULL, E'Power', E'+4000', E'armor', NULL),
(E'Glamered', NULL, E'Power', E'+4000', E'weapon', NULL),
(E'Resizing', NULL, E'Power', E'+4000', E'weapon', NULL),
(E'Wyroot (3 Point)', NULL, E'Material', E'+4000', E'weapon', NULL),
(E'Shield Boss, breakaway tower', NULL, E'Power', E'+420', E'armor', NULL),
(E'Acid Resistance, Improved', NULL, E'Power', E'+42000', E'armor', NULL),
(E'Cold Resistance, improved', NULL, E'Power', E'+42000', E'armor', NULL),
(E'Electricity Resistance, Improved', NULL, E'Power', E'+42000', E'armor', NULL),
(E'Fire Resistance, Improved', NULL, E'Power', E'+42000', E'armor', NULL),
(E'Sonic Resistance, improved', NULL, E'Power', E'+42000', E'armor', NULL),
(E'Infecting Spike', NULL, E'Power', E'+42350', E'armor', NULL),
(E'Shield Boss, mwk hooked tower', NULL, E'Power', E'+430', E'armor', NULL),
(E'Amorphous', NULL, E'Power', E'+4500', E'armor', NULL),
(E'Restful', NULL, E'Power', E'+4500', E'armor', NULL),
(E'Shield Boss, mwk breakaway tower', NULL, E'Power', E'+470', E'armor', NULL),
(E'Etherealness', NULL, E'Power', E'+49000', E'armor', NULL),
(E'Undead controlling', NULL, E'Power', E'+49000', E'armor', NULL),
(E'Sawback Sword', NULL, E'Power', E'+5', E'weapon', NULL),
(E'Armor Spikes', NULL, E'Power', E'+50', E'armor', NULL),
(E'Throwing (Metal Shields)', NULL, E'Power', E'+50', E'armor', NULL),
(E'Throwing (Wooden Shields)', NULL, E'Power', E'+50', E'armor', NULL),
(E'Burnished', NULL, E'Power', E'+500', E'armor', NULL),
(E'Slumbering', NULL, E'Power', E'+500', E'armor', NULL),
(E'Balanced (Fortitude)', 1, E'Power', NULL, E'armor', NULL),
(E'Balanced (Reflex)', 1, E'Power', NULL, E'armor', NULL),
(E'Balanced (Will)', 1, E'Power', NULL, E'armor', NULL),
(E'Bane', 1, E'Power', NULL, E'weapon', NULL),
(E'Bashing', 1, E'Power', NULL, E'armor', NULL),
(E'Beaming', 1, E'Power', NULL, E'weapon', NULL),
(E'Benevolent', 1, E'Power', NULL, E'armor', NULL),
(E'Benevolent', 1, E'Power', NULL, E'weapon', NULL),
(E'Bewildering', 1, E'Power', NULL, E'weapon', NULL),
(E'Billowing', 1, E'Power', NULL, E'armor', NULL),
(E'Bitter', 1, E'Power', NULL, E'armor', NULL),
(E'Blinding', 1, E'Power', NULL, E'armor', NULL),
(E'Blood-hunting', 1, E'Power', NULL, E'weapon', NULL),
(E'Bloodsong', 1, E'Power', NULL, E'weapon', NULL),
(E'Bolstering', 1, E'Power', NULL, E'armor', NULL),
(E'Brawling', 1, E'Power', NULL, E'weapon', NULL),
(E'Breaking', 1, E'Power', NULL, E'weapon', NULL),
(E'Called', 1, E'Power', NULL, E'weapon', NULL),
(E'Calming', 1, E'Power', NULL, E'armor', NULL),
(E'Catalytic', 1, E'Power', NULL, E'weapon', NULL),
(E'Champion', 1, E'Power', NULL, E'armor', NULL),
(E'Clangorous', 1, E'Power', NULL, E'armor', NULL),
(E'Clustershot', 1, E'Power', NULL, E'weapon', NULL),
(E'Cocooning', 1, E'Power', NULL, E'armor', NULL),
(E'Compassionate', 1, E'Power', NULL, E'weapon', NULL),
(E'Conductive', 1, E'Power', NULL, E'weapon', NULL),
(E'Confounding', 1, E'Power', NULL, E'weapon', NULL),
(E'Conserving', 1, E'Power', NULL, E'weapon', NULL),
(E'Corrosive', 1, E'Power', NULL, E'weapon', NULL),
(E'Countering', 1, E'Power', NULL, E'weapon', NULL),
(E'Courageous', 1, E'Power', NULL, E'weapon', NULL),
(E'Cruel', 1, E'Power', NULL, E'weapon', NULL),
(E'Crusading', 1, E'Power', NULL, E'armor', NULL),
(E'Cunning', 1, E'Power', NULL, E'weapon', NULL),
(E'Dastard', 1, E'Power', NULL, E'armor', NULL),
(E'Dazzling Radiance', 1, E'Power', NULL, E'weapon', NULL),
(E'Deadly', 1, E'Power', NULL, E'weapon', NULL),
(E'Deathless', 1, E'Power', NULL, E'armor', NULL),
(E'Debilitating', 1, E'Power', NULL, E'weapon', NULL),
(E'Deceptive', 1, E'Power', NULL, E'weapon', NULL),
(E'Defending', 1, E'Power', NULL, E'weapon', NULL),
(E'Defiant', 1, E'Power', NULL, E'armor', NULL),
(E'Disjoining', 1, E'Power', NULL, E'weapon', NULL),
(E'Dispelling', 1, E'Power', NULL, E'weapon', NULL),
(E'Distance', 1, E'Power', NULL, E'weapon', NULL),
(E'Distracting', 1, E'Power', NULL, E'weapon', NULL),
(E'Driving', 1, E'Power', NULL, E'weapon', NULL),
(E'Drowscorge', 1, E'Power', NULL, E'weapon', NULL),
(E'Dueling', 1, E'Power', NULL, E'weapon', NULL),
(E'Evolving', 1, E'Power', NULL, E'armor', NULL),
(E'Fate-Stealing', 1, E'Power', NULL, E'weapon', NULL),
(E'Fercent', 1, E'Power', NULL, E'weapon', NULL),
(E'Flamboyant', 1, E'Power', NULL, E'weapon', NULL),
(E'Flaming', 1, E'Power', NULL, E'weapon', NULL),
(E'Folding', 1, E'Power', NULL, E'armor', NULL),
(E'Fortification (light)', 1, E'Power', NULL, E'armor', NULL),
(E'Fortuitous', 1, E'Power', NULL, E'weapon', NULL),
(E'Frost', 1, E'Power', NULL, E'weapon', NULL),
(E'Furious', 1, E'Power', NULL, E'weapon', NULL),
(E'Ghost Touch', 1, E'Power', NULL, E'weapon', NULL),
(E'Grayflame', 1, E'Power', NULL, E'weapon', NULL),
(E'Grinding', 1, E'Power', NULL, E'armor', NULL),
(E'Grounding', 1, E'Power', NULL, E'weapon', NULL),
(E'Growing', 1, E'Power', NULL, E'weapon', NULL),
(E'Guardian', 1, E'Power', NULL, E'weapon', NULL),
(E'Guarding', 1, E'Power', NULL, E'armor', NULL),
(E'Guided', 1, E'Power', NULL, E'weapon', NULL),
(E'Healer\'s Sorrow', 1, E'Power', NULL, E'weapon', NULL),
(E'Heartseeker', 1, E'Power', NULL, E'weapon', NULL),
(E'Heraldic', 1, E'Power', NULL, E'armor', NULL),
(E'Huntsman', 1, E'Power', NULL, E'weapon', NULL),
(E'Impervious', 1, E'Power', NULL, E'armor', NULL),
(E'Injecting', 1, E'Power', NULL, E'weapon', NULL),
(E'Inspired', 1, E'Power', NULL, E'weapon', NULL),
(E'Jurist', 1, E'Power', NULL, E'weapon', NULL),
(E'Keen', 1, E'Power', NULL, E'weapon', NULL),
(E'Ki Focus', 1, E'Power', NULL, E'weapon', NULL),
(E'Kinslayer', 1, E'Power', NULL, E'weapon', NULL),
(E'Leveraging', 1, E'Power', NULL, E'weapon', NULL),
(E'Limning', 1, E'Power', NULL, E'weapon', NULL),
(E'Lucky', 1, E'Power', NULL, E'weapon', NULL),
(E'Menacing', 1, E'Power', NULL, E'weapon', NULL),
(E'Merciful', 1, E'Power', NULL, E'weapon', NULL),
(E'Mighty Cleaving', 1, E'Power', NULL, E'weapon', NULL),
(E'Mimetic', 1, E'Power', NULL, E'weapon', NULL),
(E'Mirrored', 1, E'Power', NULL, E'armor', NULL),
(E'Miserable', 1, E'Power', NULL, E'weapon', NULL),
(E'Mythic Bane', 1, E'Power', NULL, E'weapon', NULL),
(E'Neutralizing', 1, E'Power', NULL, E'weapon', NULL),
(E'Ominuous', 1, E'Power', NULL, E'weapon', NULL),
(E'Patriotic', 1, E'Power', NULL, E'weapon', NULL),
(E'Pitfall', 1, E'Power', NULL, E'weapon', NULL),
(E'Planar', 1, E'Power', NULL, E'weapon', NULL),
(E'Plummeting', 1, E'Power', NULL, E'weapon', NULL),
(E'Poisoning', 1, E'Power', NULL, E'armor', NULL),
(E'Quenching', 1, E'Power', NULL, E'weapon', NULL),
(E'Ramming', 1, E'Power', NULL, E'armor', NULL),
(E'Rebounding', 1, E'Power', NULL, E'armor', NULL),
(E'Reliable', 1, E'Power', NULL, E'weapon', NULL),
(E'Resonating', 1, E'Power', NULL, E'armor', NULL),
(E'Returning', 1, E'Power', NULL, E'weapon', NULL),
(E'Rusting', 1, E'Power', NULL, E'weapon', NULL),
(E'Sacred', 1, E'Power', NULL, E'weapon', NULL),
(E'Sapping', 1, E'Power', NULL, E'weapon', NULL),
(E'Seaborne', 1, E'Power', NULL, E'weapon', NULL),
(E'Seeking', 1, E'Power', NULL, E'weapon', NULL),
(E'Shadowshooting', 1, E'Power', NULL, E'weapon', NULL),
(E'Shock', 1, E'Power', NULL, E'weapon', NULL),
(E'Singing', 1, E'Power', NULL, E'armor', NULL),
(E'Skewering', 1, E'Power', NULL, E'weapon', NULL),
(E'Slithering', 1, E'Power', NULL, E'weapon', NULL),
(E'Smashing', 1, E'Power', NULL, E'weapon', NULL),
(E'Sparkfly Crystal', 1, E'Power', NULL, E'weapon', NULL),
(E'Spell Hurling', 1, E'Power', NULL, E'weapon', NULL),
(E'Spell Storing', 1, E'Power', NULL, E'armor', NULL),
(E'Spell Storing', 1, E'Power', NULL, E'weapon', NULL),
(E'Spellrending', 1, E'Power', NULL, E'armor', NULL),
(E'Spellsing', 1, E'Power', NULL, E'armor', NULL),
(E'Spirit-hunting', 1, E'Power', NULL, E'weapon', NULL),
(E'Stanching', 1, E'Power', NULL, E'armor', NULL),
(E'Sticky', 1, E'Power', NULL, E'weapon', NULL),
(E'Summon bane', 1, E'Power', NULL, E'weapon', NULL),
(E'Terrain-Striding', 1, E'Power', NULL, E'armor', NULL),
(E'Thawing', 1, E'Power', NULL, E'weapon', NULL),
(E'Throwing', 1, E'Power', NULL, E'weapon', NULL),
(E'Thundering', 1, E'Power', NULL, E'weapon', NULL),
(E'Training', 1, E'Power', NULL, E'weapon', NULL),
(E'Trapwarding', 1, E'Power', NULL, E'armor', NULL),
(E'Unaligned', 1, E'Power', NULL, E'weapon', NULL),
(E'Underwater', 1, E'Power', NULL, E'weapon', NULL),
(E'Valiant', 1, E'Power', NULL, E'weapon', NULL),
(E'Vampiric (Horror Adventure)', 1, E'Power', NULL, E'weapon', NULL),
(E'Veering', 1, E'Power', NULL, E'weapon', NULL),
(E'Vicious', 1, E'Power', NULL, E'weapon', NULL),
(E'Virulent', 1, E'Power', NULL, E'weapon', NULL),
(E'Vouchsafing', 1, E'Power', NULL, E'armor', NULL),
(E'Warding', 1, E'Power', NULL, E'armor', NULL),
(E'Withstanding', 1, E'Power', NULL, E'armor', NULL),
(E'Adamant', 2, E'Power', NULL, E'armor', NULL),
(E'Advancing', 2, E'Power', NULL, E'weapon', NULL),
(E'Anarchic', 2, E'Power', NULL, E'weapon', NULL),
(E'Anchoring', 2, E'Power', NULL, E'weapon', NULL),
(E'Animated', 2, E'Power', NULL, E'armor', NULL),
(E'Arrow Deflection', 2, E'Power', NULL, E'armor', NULL),
(E'Axiomatic', 2, E'Power', NULL, E'weapon', NULL),
(E'Bloodthirsty', 2, E'Power', NULL, E'armor', NULL),
(E'Burning', 2, E'Power', NULL, E'weapon', NULL),
(E'Corrosive Burst', 2, E'Power', NULL, E'weapon', NULL),
(E'Covetous', 2, E'Power', NULL, E'weapon', NULL),
(E'Culling', 2, E'Power', NULL, E'weapon', NULL),
(E'Cyclonic', 2, E'Power', NULL, E'weapon', NULL),
(E'Dazzling', 2, E'Power', NULL, E'weapon', NULL),
(E'Defiant', 2, E'Power', NULL, E'weapon', NULL),
(E'Designating, Lesser', 2, E'Power', NULL, E'weapon', NULL),
(E'Dispelling Burst', 2, E'Power', NULL, E'weapon', NULL),
(E'Disruption', 2, E'Power', NULL, E'weapon', NULL),
(E'Distracting, Greater', 2, E'Power', NULL, E'weapon', NULL),
(E'Dominant', 2, E'Power', NULL, E'weapon', NULL),
(E'Endless Ammunition', 2, E'Power', NULL, E'weapon', NULL),
(E'Flaming Burst', 2, E'Power', NULL, E'weapon', NULL),
(E'Frosted', 2, E'Power', NULL, E'armor', NULL),
(E'Furyborn', 2, E'Power', NULL, E'weapon', NULL),
(E'Ghost Spike', 2, E'Power', NULL, E'armor', NULL),
(E'Glitterwake', 2, E'Power', NULL, E'weapon', NULL),
(E'Glorious', 2, E'Power', NULL, E'weapon', NULL),
(E'Guarding, Greater', 2, E'Power', NULL, E'armor', NULL),
(E'Harvesting', 2, E'Power', NULL, E'weapon', NULL),
(E'Heretical', 2, E'Power', NULL, E'weapon', NULL),
(E'Holy', 2, E'Power', NULL, E'weapon', NULL),
(E'Icy Burst', 2, E'Power', NULL, E'weapon', NULL),
(E'Igniting', 2, E'Power', NULL, E'weapon', NULL),
(E'Impact', 2, E'Power', NULL, E'weapon', NULL),
(E'Invigorating', 2, E'Power', NULL, E'weapon', NULL),
(E'Jarring', 2, E'Power', NULL, E'armor', NULL),
(E'Jawbreaker', 2, E'Power', NULL, E'armor', NULL),
(E'Jealous', 2, E'Power', NULL, E'weapon', NULL),
(E'Ki Intensifying', 2, E'Power', NULL, E'weapon', NULL),
(E'Legbreaker', 2, E'Power', NULL, E'weapon', NULL),
(E'Liberating', 2, E'Power', NULL, E'weapon', NULL),
(E'Lifesurge', 2, E'Power', NULL, E'weapon', NULL),
(E'Mastering', 2, E'Power', NULL, E'armor', NULL),
(E'Merging', 2, E'Power', NULL, E'armor', NULL),
(E'Mind Buttressing', 2, E'Power', NULL, E'armor', NULL),
(E'Miserly', 2, E'Power', NULL, E'weapon', NULL),
(E'Negating', 2, E'Power', NULL, E'weapon', NULL),
(E'Obliviating', 2, E'Power', NULL, E'weapon', NULL),
(E'Parasitic', 2, E'Power', NULL, E'weapon', NULL),
(E'Peaceful', 2, E'Power', NULL, E'weapon', NULL),
(E'Penetrating', 2, E'Power', NULL, E'weapon', NULL),
(E'Phantasmal', 2, E'Power', NULL, E'armor', NULL),
(E'Phase Locking', 2, E'Power', NULL, E'weapon', NULL),
(E'Planestriking', 2, E'Power', NULL, E'weapon', NULL),
(E'Potent', 2, E'Power', NULL, E'weapon', NULL),
(E'Quaking', 2, E'Power', NULL, E'weapon', NULL),
(E'Rampaging', 2, E'Power', NULL, E'armor', NULL),
(E'Reliable, Greater', 2, E'Power', NULL, E'weapon', NULL),
(E'Sadistic', 2, E'Power', NULL, E'weapon', NULL),
(E'Shadow Blending', 2, E'Power', NULL, E'armor', NULL),
(E'Sharding', 2, E'Power', NULL, E'weapon', NULL),
(E'Shattering', 2, E'Power', NULL, E'weapon', NULL),
(E'Shocking Burst', 2, E'Power', NULL, E'weapon', NULL),
(E'Silencing', 2, E'Power', NULL, E'weapon', NULL),
(E'Sniping', 2, E'Power', NULL, E'weapon', NULL),
(E'Spell Dodging', 2, E'Power', NULL, E'armor', NULL),
(E'Spell Resistance (13)', 2, E'Power', NULL, E'armor', NULL),
(E'Stalking', 2, E'Power', NULL, E'weapon', NULL),
(E'Steaming', 2, E'Power', NULL, E'armor', NULL),
(E'Toxic', 2, E'Power', NULL, E'weapon', NULL),
(E'Treasonous', 2, E'Power', NULL, E'weapon', NULL),
(E'Truthful', 2, E'Power', NULL, E'weapon', NULL),
(E'Tyrannical', 2, E'Power', NULL, E'weapon', NULL),
(E'Unholy', 2, E'Power', NULL, E'weapon', NULL),
(E'Unseen', 2, E'Power', NULL, E'weapon', NULL),
(E'Vampiric', 2, E'Power', NULL, E'weapon', NULL),
(E'Vampiric, Greater', 2, E'Power', NULL, E'weapon', NULL),
(E'Volcanic', 2, E'Power', NULL, E'armor', NULL),
(E'Weeping', 2, E'Power', NULL, E'armor', NULL),
(E'Wounding', 2, E'Power', NULL, E'weapon', NULL),
(E'Arrow-Collecting', 3, E'Power', NULL, E'armor', NULL),
(E'Brawling', 3, E'Power', NULL, E'armor', NULL),
(E'Cotraveling', 3, E'Power', NULL, E'armor', NULL),
(E'Deflecting', 3, E'Power', NULL, E'armor', NULL),
(E'Exhausting', 3, E'Power', NULL, E'weapon', NULL),
(E'Flamboyant, greater', 3, E'Power', NULL, E'weapon', NULL),
(E'Fortification (moderate)', 3, E'Power', NULL, E'armor', NULL),
(E'Ghost Touch', 3, E'Power', NULL, E'armor', NULL),
(E'Gory', 3, E'Power', NULL, E'weapon', NULL),
(E'Invulnerability', 3, E'Power', NULL, E'armor', NULL),
(E'Lucky, Greater', 3, E'Power', NULL, E'weapon', NULL),
(E'ifying', 3, E'Power', NULL, E'weapon', NULL),
(E'Redeemed', 3, E'Power', NULL, E'weapon', NULL),
(E'Repositioning', 3, E'Power', NULL, E'weapon', NULL),
(E'Sensing', 3, E'Power', NULL, E'armor', NULL),
(E'Sonic Boom', 3, E'Power', NULL, E'weapon', NULL),
(E'Speed', 3, E'Power', NULL, E'weapon', NULL),
(E'Spell Resistance (15)', 3, E'Power', NULL, E'armor', NULL),
(E'Spellstealing', 3, E'Power', NULL, E'weapon', NULL),
(E'Tailwind', 3, E'Power', NULL, E'weapon', NULL),
(E'Titanic', 3, E'Power', NULL, E'armor', NULL),
(E'Umbral', 3, E'Power', NULL, E'weapon', NULL),
(E'Wild', 3, E'Power', NULL, E'armor', NULL),
(E'Bastion', 4, E'Power', NULL, E'armor', NULL),
(E'Brilliant Energy', 4, E'Power', NULL, E'weapon', NULL),
(E'Dancing', 4, E'Power', NULL, E'weapon', NULL),
(E'Denying', 4, E'Power', NULL, E'armor', NULL),
(E'Designating, Greater', 4, E'Power', NULL, E'weapon', NULL),
(E'Nimble Shot', 4, E'Power', NULL, E'weapon', NULL),
(E'Second Chance', 4, E'Power', NULL, E'weapon', NULL),
(E'Spell Resistance (17)', 4, E'Power', NULL, E'armor', NULL),
(E'Dread Wing', 5, E'Power', NULL, E'armor', NULL),
(E'Flying', 5, E'Power', NULL, E'weapon', NULL),
(E'Fortification (heavy)', 5, E'Power', NULL, E'armor', NULL),
(E'Heart-Piercing', 5, E'Power', NULL, E'weapon', NULL),
(E'Interfering', 5, E'Power', NULL, E'weapon', NULL),
(E'Reflecting', 5, E'Power', NULL, E'armor', NULL),
(E'Spell Resistance (19)', 5, E'Power', NULL, E'armor', NULL),
(E'Spell Siphon', 5, E'Power', NULL, E'weapon', NULL),
(E'Unbowed', 5, E'Power', NULL, E'armor', NULL),
(E'Vorpal', 5, E'Power', NULL, E'weapon', NULL),
(E'+2', 2, E'Power', NULL, E'armor', NULL),
(E'+2', 2, E'Power', NULL, E'weapon', NULL),
(E'+3', 3, E'Power', NULL, E'armor', NULL),
(E'+3', 3, E'Power', NULL, E'weapon', NULL),
(E'+4', 4, E'Power', NULL, E'armor', NULL),
(E'+4', 4, E'Power', NULL, E'weapon', NULL),
(E'+5', 5, E'Power', NULL, E'armor', NULL),
(E'+5', 5, E'Power', NULL, E'weapon', NULL);
